wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1705929907.86072
    t:
      1:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 15
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 15
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
