model_options:
  test_size: 0.15
  train_size: 0.15
  random_state: 3
  features:
    - national_rank
    - quality_of_education
    - alumni_employment
    - quality_of_faculty
    - publications
    - patents
    - score
    - citations
    - influence